
version: "3"

interval: 200ms

vars:
  NAME: "natster"

tasks:
  ui:
    dir: internal/ui/web
    cmds:
      - pnpm install
      - pnpm build
  
  natster:
    dir: natster
    sources:
      - "*.go"
    cmds:
      - go build -tags netgo -ldflags '-extldflags "-static"'  

  build:
    deps: [ui,natster]
