name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

permissions: write-all

concurrency: preview-${{ github.ref }}
defaults:
  run:
    shell: bash

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    # defaults:
    #   run:
    env:
      HUGO_VERSION: 0.123.8
    steps:
      - 
        name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - 
        name: Install Dart Sass
        run: sudo snap install dart-sass
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - 
        name: Install Node.js dependencies
        working-directory: ./docs
        run: "ls -lah && pwd && [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - 
        name: Build with Hugo
        working-directory: ./docs
        if: github.event.action != 'closed' # skip the build if the PR has been closed
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify
      - 
        name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/public/
          custom-url: "docs.natster.io/pr-preview/pr-86"
