name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions: {}  # future-proof, preemptively move permissions into jobs level

concurrency:
  group: "release"
  cancel-in-progress: false

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    concurrency:
      group: release-installer-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
          # Caching: we are making release artifacts, and unfortunately we need
          # to ensure that the cache is not poisonable.
          cache: false
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --verbose --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_RELEASE }}
