name: 'UI'
on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:

  check-ui:
    runs-on: ubuntu-latest
    name: Check UI for edits
    outputs:
      status: ${{ steps.ui-edited.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Determine if changes to UI directory
        id: ui-edited
        shell: bash
        run: |
          : "${GITHUB_BASE_REF:?missing GITHUB_BASE_REF on push, fixme}"
          changes="$(git diff-tree -r --name-only "origin/$GITHUB_BASE_REF" HEAD -- natster-io)"
          if [[ -n "$changes" ]]; then
            echo >> "$GITHUB_OUTPUT" "any_changed=true"
          else
            echo >> "$GITHUB_OUTPUT" "any_changed=false"
          fi

  check-formatter:
    runs-on: ubuntu-latest
    name: Checks to see if UI code is formatted
    needs: check-ui
    if: needs.check-ui.outputs.status
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: Install UI deps
        working-directory: ./natster-io
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash sh -
          ~/.local/share/pnpm/pnpm install
      -
        name: Check formatting
        working-directory: ./natster-io
        run: ~/.local/share/pnpm/pnpm run check-formatting

  build-ui:
    runs-on: ubuntu-latest
    name: Builds UI if edits found
    needs: check-ui
    if: needs.check-ui.outputs.status
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: Build ui
        working-directory: ./natster-io
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash sh -
          ~/.local/share/pnpm/pnpm install
          ~/.local/share/pnpm/pnpm build-only --outDir server/dist
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      -
        name: Build server
        working-directory: ./natster-io/server
        run: |
          go build -tags netgo -ldflags '-extldflags "-static"' -o natster-ui-server
          go build -tags with_tailscale -o natster-ui-server-ts
      -
        name: Archive server binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          retention-days: 1
          path: |
            ./natster-io/server/natster-ui-server*
