name: 'UI - Prod Env'
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

# For tag pushes, we always build and deploy

permissions: {}

jobs:
  build-ui:
    runs-on: ubuntu-latest
    name: Builds UI if edits found
    permissions:
      contents: read   # clone repo
      actions: write   # upload artifacts
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      -
        name: Build ui
        working-directory: ./natster-io
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | SHELL=bash bash -
          ~/.local/share/pnpm/pnpm install
          ~/.local/share/pnpm/pnpm build-only --outDir server/dist
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          # Caching: we are making release artifacts, and unfortunately we need
          # to ensure that the cache is not poisonable.
          cache: false
      -
        name: Build server
        working-directory: ./natster-io/server
        run: |
          go build -o natster-ui-server
      -
        name: Archive server binaries
        uses: actions/upload-artifact@v4
        with:
          name: web_server
          retention-days: 1
          path: |
            ./natster-io/server/natster-ui-server

  deployment:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    needs: build-ui
    environment:
      name: Prod
      url: https://natster.io
    permissions:
      actions: read    # download artifacts
      id-token: write  # OIDC exchange for tailscale
    steps:
      -
        name: Download server artifact
        uses: actions/download-artifact@v4
        with:
          name: web_server
      -
        name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:natster
      # No SSH keys needed for SSH below, it's using Tailscale connection ambient identity
      -
        name: Stop Prod Server
        run: |
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@natster-ui.pig-bee.ts.net systemctl stop natster-ui-prod.service
      -
        name: Update Prod server on host
        run: |
          scp -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" natster-ui-server root@natster-ui.pig-bee.ts.net:/usr/local/bin/natster-ui-server
      -
        name: Restart Prod Server
        run: |
          ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" root@natster-ui.pig-bee.ts.net systemctl start natster-ui-prod.service

